# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Customtest():
  def setup(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def tearmethod(self):
    self.driver.quit()
  
  def customtest(self):
    self.driver.get("https://bhavin121.github.io/")
    self.driver.set_window_size(850, 642)
    self.driver.find_element(By.CSS_SELECTOR, ".Login:nth-child(4)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("hannah@gmail.com")
    self.driver.find_element(By.ID, "pass").click()
    self.driver.find_element(By.ID, "pass").send_keys("hannahhello")
    self.driver.find_element(By.ID, "signIn").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".recipeBox:nth-child(3) .expandRead").click()
    time.sleep(5)
    self.driver.close()
  
test = Customtest()
test.setup()
test.customtest()
test.tearmethod()